[package]
categories           = ["cryptography", "encoding"]
description          = "AEAD encryption with integrated serialization for Rust types"
edition.workspace    = true
keywords             = ["security", "encryption", "aead", "serialization"]
license.workspace    = true
name                 = "memcrypt"
repository.workspace = true
version.workspace    = true

[lib]
path = "src/lib.rs"

[dependencies]
memrand.workspace = true
subtle.workspace  = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace  = true
