[package]
name = "memvault_core"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
default = []
no_std = []

[dependencies]
memcodec = { workspace = true, features = ["zeroize"]}
memhkdf.workspace = true
memalloc.workspace = true
membuffer.workspace = true
memguard.workspace = true
memrand.workspace = true
memcrypt.workspace = true
memzer.workspace = true
memaead.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dev-dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
libseccomp.workspace = true
