[package]
name = "memvault_core"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
default = []
no_std = []

[dependencies]
membuffer.workspace = true
memguard.workspace = true
memrand.workspace = true
thiserror.workspace = true

[dev-dependencies]
memzer.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
libc.workspace = true
libseccomp.workspace = true
