[package]
authors              = ["Federico Hoerth <memparanoid@gmail.com>"]
categories           = ["encoding", "memory-management"]
description          = "Allocation-free, zeroizing serialization for sensitive data"
edition.workspace    = true
keywords             = ["serialization", "zeroize", "security"]
license.workspace    = true
name                 = "memcode_core"
repository.workspace = true
version.workspace    = true

[lib]
path = "src/lib.rs"

[dependencies]
thiserror.workspace = true
zeroize.workspace   = true

[dev-dependencies]
insta.workspace     = true
pastey.workspace    = true
proptest.workspace  = true
seq-macro.workspace = true

[features]
test_utils = []
