[package]
authors              = ["Federico Hoerth <memparanoid@gmail.com>"]
categories           = ["encoding", "memory-management"]
description          = "Core implementation for memcodec"
edition.workspace    = true
keywords             = ["codec", "zeroize", "security", "encoding"]
license.workspace    = true
name                 = "memcodec_core"
repository.workspace = true
version.workspace    = true

[lib]
path = "src/lib.rs"

[features]
default = []
zeroize = ["dep:smallvec", "dep:zeroize"]
benchmark = []
test_utils = ["zeroize"]

[dependencies]
memutil.workspace   = true
memzer.workspace    = true
smallvec = { workspace = true, optional = true }
thiserror.workspace = true
zeroize = { workspace = true, optional = true }

[dependencies.memalloc]
workspace = true
features  = ["unsafe"]

[dev-dependencies]
memalloc = { workspace = true, features = ["test_utils"] }
zeroize.workspace = true
