[package]
name = "memvault"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
default = []
no_std = ["memvault_core/no_std"]

[dependencies]
memvault_core = { path = "core" }
memvault_derive = { path = "derive" }

[dev-dependencies]
