[package]
categories           = ["memory-management", "no-std"]
description          = "Core zeroing traits and protected memory primitives"
edition.workspace    = true
keywords             = ["security", "memory", "zeroize", "guards"]
license.workspace    = true
name                 = "memzer-core"
repository.workspace = true
version.workspace    = true

[lib]
path = "src/lib.rs"

[dependencies]
zeroize.workspace = true

[dev-dependencies]
proptest.workspace = true
