[package]
name = "wasm-demo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.106"
redoubt = { workspace = true, features = ["no_std"] }

[profile.release]
opt-level = "z"
lto = true
