[package]
authors              = ["Federico Hoerth <memparanoid@gmail.com>"]
categories           = ["development-tools::procedural-macro-helpers"]
description          = "Derive macros for memcode serialization"
edition.workspace    = true
keywords             = ["derive", "macro", "serialization"]
license.workspace    = true
name                 = "memcode_derive"
repository.workspace = true
version.workspace    = true

[lib]
path       = "src/lib.rs"
proc-macro = true

[dependencies]
memcode_core.workspace     = true
proc-macro-crate.workspace = true
proc-macro2.workspace      = true
quote.workspace            = true
syn.workspace              = true
zeroize.workspace          = true

[dev-dependencies]
insta.workspace        = true
prettyplease.workspace = true
trybuild.workspace     = true
