[package]
authors              = ["Federico Hoerth <memparanoid@gmail.com>"]
categories           = ["development-tools::procedural-macro-helpers"]
description          = "Derive macros for memcode serialization"
edition.workspace    = true
keywords             = ["derive", "macro", "serialization"]
license.workspace    = true
name                 = "memcode_derive"
repository.workspace = true
version.workspace    = true

[lib]
path       = "src/lib.rs"
proc-macro = true

[dependencies]
memcode_core.workspace = true
proc-macro-crate       = "3.4.0"
proc-macro2            = "1.0.103"
quote                  = "1.0.41"
syn                    = "2.0.108"
zeroize.workspace      = true

[dev-dependencies]
insta.workspace = true
prettyplease    = "0.2.37"
trybuild        = "1.0"
