[package]
name = "redoubt-vault-core"
authors = ["Federico Hoerth <memparanoid@gmail.com>"]
categories = ["cryptography", "memory-management"]
description = "Core implementation for redoubt-vault encrypted storage"
edition.workspace = true
keywords = ["vault", "encryption", "secrets", "aead", "zeroize"]
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
no_std = []
guard = ["redoubt-guard/guard"]
internal-forensics = []
asm = ["redoubt-rand/asm", "redoubt-aead/asm"]

[dependencies]
redoubt-codec = { workspace = true, features = ["zeroize"]}
redoubt-alloc.workspace = true
redoubt-secret.workspace = true
redoubt-buffer.workspace = true
redoubt-guard.workspace = true
redoubt-rand.workspace = true
redoubt-zero.workspace = true
redoubt-aead.workspace = true
thiserror.workspace = true

[dev-dependencies]
redoubt-codec = { workspace = true, features = ["test-utils"] }
redoubt-test-utils.workspace = true
redoubt-util.workspace = true
redoubt-aead = { workspace = true, features = ["test-utils"] }


[target.'cfg(unix)'.dev-dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
libseccomp.workspace = true
