[package]
authors = ["Federico Hoerth <memparanoid@gmail.com>"]
edition = "2024"
name    = "memcode_derive"
version = "1.0.0"

[lib]
path       = "src/lib.rs"
proc-macro = true

[dependencies]
memcode_core     = { path = "../core" }
proc-macro-crate = "3.4.0"
proc-macro2      = "1.0.103"
quote            = "1.0.41"
syn              = "2.0.108"
zeroize          = { version = "1.8.1", features = ["zeroize_derive"] }

[dev-dependencies]
insta        = { version = "1.43.2", features = ["redactions"] }
prettyplease = "0.2.37"
trybuild     = "1.0"
