[package]
name = "redoubt-forensics"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "test_redoubt_leaks"
path = "src/bin/test_redoubt_leaks.rs"


[features]
default = []
__internal__forensics = ["redoubt/__internal__forensics"]

[dependencies]
redoubt = { path = "../../crates/redoubt" }
libc.workspace = true
