[package]
name = "redoubt-forensics"
authors = ["Federico Hoerth <memparanoid@gmail.com>"]
categories = ["development-tools::debugging"]
description = "Memory forensics tools for Redoubt"
edition.workspace = true
keywords = ["forensics", "memory", "analysis", "debugging"]
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[[bin]]
name = "redoubt_trace_report"
path = "src/bin/redoubt_trace_report.rs"


[features]
default = []
internal-forensics = ["redoubt/internal-forensics"]

[dependencies]
redoubt = { workspace = true, features = ["asm"] }
libc.workspace = true
