[package]
authors = ["Federico Hoerth <memparanoid@gmail.com>"]
edition = "2024"
name    = "memcode"
version = "1.0.0"

[lib]
path = "src/lib.rs"

[dependencies]
memcode_core   = { path = "./core" }
memcode_derive = { path = "./derive" }

[features]
test_utils = ["memcode_core/test_utils"]
