[package]
name = "wasm-example"
authors = ["Federico Hoerth <memparanoid@gmail.com>"]
categories = ["wasm", "cryptography"]
description = "WASM example for Redoubt"
edition.workspace = true
keywords = ["wasm", "example", "redoubt"]
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.106"
redoubt.workspace = true
