[package]
name = "wallet-example"
authors = ["Federico Hoerth <memparanoid@gmail.com>"]
categories = ["cryptography", "memory-management"]
description = "Wallet example for Redoubt"
edition.workspace = true
keywords = ["wallet", "example", "redoubt"]
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[features]
test-utils = []

[dependencies]
redoubt = { workspace = true, features = ["full"] }
