[package]
authors              = ["Federico Hoerth <memparanoid@gmail.com>"]
categories           = ["encoding", "memory-management"]
description          = "Derive macros for memcodec"
edition.workspace    = true
keywords             = ["codec", "zeroize", "security", "encoding"]
license.workspace    = true
name                 = "memcodec_derive"
repository.workspace = true
version.workspace    = true

[lib]
proc-macro = true
path = "src/lib.rs"

[features]
default = ["zeroize"]
zeroize = ["memcodec_core/zeroize"]

[dependencies]
proc-macro-crate.workspace = true
proc-macro2.workspace      = true
quote.workspace            = true
syn.workspace              = true

[dev-dependencies]
memzer.workspace = true
insta.workspace         = true
memcodec_core.workspace = true
prettyplease.workspace  = true
