[package]
authors              = ["Federico Hoerth <memparanoid@gmail.com>"]
categories           = ["encoding", "memory-management"]
description          = "Derive macros for memcodec"
edition.workspace    = true
keywords             = ["codec", "zeroize", "security", "encoding"]
license.workspace    = true
name                 = "memcodec_derive"
repository.workspace = true
version.workspace    = true

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2.workspace = true
quote.workspace       = true
syn.workspace         = true
